Add Nexell/RK SoCs, fix RK3399 stepping info
hrw/arm-socs-table pull request #85
Opened 2023-01-31 12:54 UTC by ThomasKaiser

2023-01-31 14:02 UTC, hrw requested changes

2023-01-31 14:02 UTC, hrw commented on data/socs.yml
> +  name: S5P6818
I love cryptic names used by vendors. Samsung had chip with same name (or maybe it was the same one).

2023-01-31 14:07 UTC, hrw requested changes
can you squash it with previous one?

2023-01-31 15:38 UTC, ThomasKaiser commented on data/socs.yml
> +- cores:
Oh, I thought the X-Gene 1 is `revision: 0x1, variant: 0x0` while the APM883208-X1 is `0x0, 0x0`.

Ah, now I understand. You provided contents of `/proc/cpuinfo` in https://github.com/hrw/arm-socs-table/commit/d528f259a7974526af9171f49b5fcf1b79f2d0e3 yourself so X-Gene 1 is not `revision: 0x1, variant: 0x0` but `revision: 0x0, variant: 0x0` instead.

Ok, then I remove the 'APM883208-X1' definition in `socs.yml` and adjust there the 'X-Gene 1' entry to `revision: 0x0`.  But then `cpu_cores.yml` also needs an adjustment, right?

    '0x0-0-0':
      aarch32: EL0-EL2
      name: X-Gene 1

2023-01-31 16:20 UTC, hrw commented on data/socs.yml
> +- cores:
X-Gene is tricky as they (APM/Ampere) used same part id for 3 generations - only revision/variant differ.

Will try to dig X-Gene 1 machine out and check details again.

2023-02-20 00:55 UTC, ThomasKaiser commented
Just to be sure. Are you waiting on some input from my side or is your 'try to dig X-Gene 1 machine out and check details again' the next step? :)

2023-02-22 23:05 UTC, closed without merging

2023-03-13 09:29 UTC, hrw commented
Merged things with exception of that ancient X-Gene entry.

I am sorry that it took insane amount of time.